export const GameConfig = {
    GAME_WIDTH: 1280,
    GAME_HEIGHT: 720,
    BACKGROUND_COLOR: '#0b0b0f',
    MAX_MOVE_DISTANCE: 180,
    SHOOT_PREVIEW_LENGTH: 180,
    ROUND_DURATION_MS: 2000,
    BARRIER_COUNT: 6,
    BARRIER_PADDING: 80,
    BARRIER_WIDTH: 16,
    BARRIER_HEIGHT: 90,
    BARRIER_MIN_X_FACTOR: 0.22,
    BARRIER_MAX_X_FACTOR: 0.78,
    BARRIER_COLOR: 0x888888,
    BARRIER_TEXTURE: 'barrier-rect',
    BOT_PLAYER_TEXTURE: 'bot-player',
    BOT_PLAYER_COLOR: 0x4aa3ff,
    BOT_AI_TEXTURE: 'bot-ai',
    BOT_AI_COLOR: 0xff6b6b,
    PARTICLE_TEXTURE: 'particle',
    PARTICLE_COLOR: 0xffffff,
    BOT_SPAWN_PADDING: 60,
    BOT_MIN_DISTANCE: 36,
    BOT_MAX_VELOCITY: 260,
    BOT_BARRIER_BOUNCE: 0.15,
    WIN_TEXT_STYLE: {
        fontFamily: 'system-ui, sans-serif',
        fontSize: '32px',
        color: '#fff',
        backgroundColor: 'rgba(0,0,0,0.7)',
        padding: { x: 24, y: 16 },
        align: 'center',
    },
    REPLAY_DELAY: 1800,
    INFO_TEXT_STYLE: {
        fontFamily: 'system-ui, sans-serif',
        fontSize: '13px',
        color: '#e6e6e6',
        backgroundColor: 'rgba(11, 11, 15, 0.65)',
        padding: { x: 10, y: 6 }
    },
    DRAG_START_THRESHOLD: 6,
    MOVE_INDICATOR_RADIUS: 16,
    SHOOT_INDICATOR_RADIUS: 32,
    SHOOT_LINE_TOLERANCE: 18,
    SHOT_START_OFFSET: 18,
    SHOT_SPREAD_DEGREES: 8,
    SHOT_SPEED: 420,
    PARTICLE_SCALE: 0.18,
    TAP_RADIUS_BASE: 64,
    PLAN_MOVE_COLOR: 0x22c55e,
    PLAN_SHOOT_COLOR: 0xf59e0b,
    AI_SHOOT_RANGE_MULTIPLIER: 4,
    AI_AVOIDANCE_ANGLE_STEP: 15,
    AI_WIGGLE_MIN_DISTANCE: 20,
    AI_WIGGLE_MAX_DISTANCE: 40,
};
